# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ba7c61ab76fe79106dedb3bbe96f0b4b96ca5d2ccaba10ea026c2c1cd8cbc7bf987bf6de46c9a502ea7c821ffdad3b60324759b03174e8b1d0dfd977d80f32

test:
  secret_key_base: 9958c0a54eed5116edd0f4ecdc701798701d6eae415939278cd7154f8545ff0ff03e9040ad037c170004f96a2f83bfad6721589fd153fe28a4a6dedf50dc405a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
